name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Navigate to the project directory
      run: cd ProyectoAsistencia

    - name: Restore dependencies
      run: dotnet restore ProyectoAsistencia.sln

    - name: Build solution
      run: dotnet build ProyectoAsistencia.sln --configuration Debug

    - name: Run tests and generate trx
      working-directory: ProyectoAsistencia.Tests
      run: dotnet test --filter FullyQualifiedName~HomeFeature --logger "trx;LogFileName=TestResults.trx"

    - name: Convert trx to JSON
      working-directory: ProyectoAsistencia.Tests/TestResults
      run: python3 trx_to_json.py TestResults.trx TestResults.json

    - name: Generate LivingDoc
      working-directory: ProyectoAsistencia.Tests
      run: livingdoc test-assembly ./bin/Debug/net8.0/ProyectoAsistencia.Tests.dll -t ./TestResults/TestResults.json -o ../ProyectoAsistenciaReport.html
