name: Generate Test Report

on: 
  push:
    branches: 
      - main  
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Install Stryker
        run: dotnet tool install -g dotnet-stryker 

      - name: Restore Stryker tools
        run: dotnet tool restore

      - name: Run Stryker
        run: |
          cd ProyectoAsistencia/ProyectoAsistencia.Tests  
          dotnet stryker 

          # Encuentra la carpeta más reciente de StrykerOutput
          latest_folder=$(ls -td StrykerOutput/* | head -n 1)

          # Crea la carpeta Reportes si no existe
          mkdir -p ../Reportes

          # Copiar el archivo de reporte HTML a la carpeta Reportes
          cp "$latest_folder/reports/mutation-report.html" ../Reportes/
          cd ..

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch --all
          git checkout gh-pages
          git add Reportes/
          git commit -m "Add Stryker report"
          git push origin gh-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Reportes
