name: Pruebas, Cobertura y Reportes en GitHub Pages

on: 
  push:
    branches: 
      - main  
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Listar archivos para verificar la estructura
        run: ls -R

      # Ejecutar pruebas unitarias con cobertura
      - name: Ejecutar pruebas y recolectar cobertura
        run: |
          cd ProyectoAsistencia/ProyectoAsistencia.Tests  
          dotnet test --collect:"XPlat Code Coverage"

      - name: Generar reporte Stryker
        run: |
          cd ProyectoAsistencia/ProyectoAsistencia.Tests
          dotnet tool install -g dotnet-stryker
          dotnet stryker
          mkdir -p Reports/Stryker
          cp StrykerOutput/*/reports/mutation-report.html Reports/Stryker/

      - name: Generar reporte de cobertura
        run: |
          cd ProyectoAsistencia/ProyectoAsistencia.Tests
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator "-reports:TestResults/**/coverage.cobertura.xml" "-targetdir:Reports/Cobertura" -reporttypes:HTML

      # Publicar ambos reportes en GitHub Pages
      - name: Publicar en GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Crear carpeta `public` con ambos reportes
          mkdir -p public
          cp -r ProyectoAsistencia/ProyectoAsistencia.Tests/Reports/* public/

          git fetch origin
          git checkout -B gh-pages
          git rm -rf ./*
          cp -r public/* .
          git add .
          git commit -m "Actualizar reportes de pruebas y cobertura"
          git push origin gh-pages --force
