name: Pruebas y Publicación en GitHub Pages

on: 
  push:
    branches: 
      - main  
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Limpiar archivos de compilación y no rastreados
      run: |
        git rm -r --cached .
        git clean -fdx
        echo -e "bin/\nobj/\n*.user\n*.log" > .gitignore
        git add .gitignore
        git commit -m "Clean untracked files and add .gitignore" || true

    - name: Ejecutar pruebas y recolectar cobertura
      run: |
        cd ProyectoAsistencia/ProyectoAsistencia.Tests  
        dotnet test --collect:"XPlat Code Coverage"
      continue-on-error: true
      
    - name: Generar reporte de Stryker
      run: |
        cd ProyectoAsistencia/ProyectoAsistencia.Tests
        dotnet tool install -g dotnet-stryker
        dotnet stryker

        # Copiar reporte de mutaciones a ReportesGH
        mkdir -p ../../ReportesGH
        latest_folder=$(ls -td StrykerOutput/* | head -n 1)
        cp "$latest_folder/reports/mutation-report.html" ../../ReportesGH/

    - name: Generar reporte de cobertura
      run: |
        cd ProyectoAsistencia/ProyectoAsistencia.Tests
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator "-reports:TestResults/**/coverage.cobertura.xml" "-targetdir:Reports/Cobertura" -reporttypes:HTML
        
        # Copiar reporte de cobertura a ReportesGH
        mkdir -p ../../ReportesGH
        cp Reports/Cobertura/index.html ../../ReportesGH/

    - name: Publicar en GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        # Copiar ReportesGH a gh-pages
        git fetch origin
        git checkout -B gh-pages
        git rm -rf ./*
        cp -r ../ReportesGH/* .
        git add .
        git commit -m "Add test and mutation reports"
        git push origin gh-pages --force
