name: "Snyk Analysis for .NET"

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x  

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 

      - name: Install Snyk CLI and snyk-to-html
        run: |
          npm install -g snyk
          npm install -g snyk-to-html

      - name: Restore and Build Project
        run: |
          cd ProyectoAsistencia
          dotnet restore
          dotnet build

      - name: Snyk Code Analysis
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          cd ProyectoAsistencia
          snyk code test --json | snyk-to-html -o code-test-results.html

      - name: Upload Code Report
        uses: actions/upload-artifact@v3s
        with:
          name: Snyk Code Report
          path: ProyectoAsistencia/code-test-results.html

      # Opcional: Análisis de contenedor solo si tienes un Dockerfile
      - name: Build Docker image
        if: exists('ProyectoAsistencia/Dockerfile')
        run: docker build -t proyectoasistencia-tests ProyectoAsistencia

      - name: Snyk Container Analysis
        if: exists('ProyectoAsistencia/Dockerfile')
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk container test proyectoasistencia-tests --json | snyk-to-html -o container-test-result.html

      - name: Upload Container Report
        if: exists('ProyectoAsistencia/Dockerfile')
        uses: actions/upload-artifact@v3
        with:
          name: Snyk Container Report
          path: container-test-result.html
