name: "Snyk Analysis with Reports"

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x  

      - name: Install Snyk CLI and snyk-to-html
        run: |
          npm install -g snyk snyk-to-html

      - name: Restore and Build Project
        run: |
          cd ProyectoAsistencia
          dotnet restore
          dotnet build

      - name: Snyk Code Analysis
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          cd ProyectoAsistencia
          snyk code test --json | snyk-to-html -o code-test-results.html

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: Snyk Code Report
          path: ProyectoAsistencia/code-test-results.html
