name: "Snyk Analysis for .NET"

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: windows-latest  # Mantener el runner Windows

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x  

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 

      - name: Install Snyk CLI manually
        run: npm install -g snyk

      - name: Restore, Test, and Analyze with Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          cd ProyectoAsistencia
          dotnet restore
          dotnet build
          snyk code test ProyectoAsistencia --json-file-output=snyk-code-results.json
          snyk container test --file=Dockerfile --json-file-output=snyk-container-results.json

      - name: Upload Snyk results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code-results.json
