name: "SonarCloud Analysis for .NET"

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: windows-latest  

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x  

      - name: Install .NET tools
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          dotnet tool install --global coverlet.console
          dotnet tool install --global dotnet-sonarscanner

      - name: Add .NET tools to PATH
        run: echo "$env:USERPROFILE\.dotnet\tools" >> $env:GITHUB_PATH
        shell: pwsh

      - name: Restore, Test, and Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd ProyectoAsistencia
          dotnet restore
          cd ProyectoAsistencia.Tests
          
          coverlet ./bin/Debug/net8.0/ProyectoAsistencia.Tests.dll --target "dotnet" --targetargs "test --no-build" -f opencover -o "coverage.xml"
          
          cd ..
          
          dotnet sonarscanner begin /k:"alvarocontreras13_calidadproyecto" /o:"alvarocontreras13" /d:sonar.cs.opencover.reportsPaths="ProyectoAsistencia.Tests/coverage.xml" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          
          dotnet build
          
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
